/**************************************************
* Class				: ConstantString
* Author			: Soljit <VW>
* Date				: 2019-07-08
* Description     	: This class contians all global strings and contants
****************************************************/
global class ConstantString { 
   	Public static final String FIXED_TYPE = 'Fixed';
    Public static final String SMALL_TYPE = 'Small';
    Public static final String VARIABLE_TYPE = 'Variable';
    Public static final String SERVICE_ADDRESS = 'Service Address';
    Public static final String PRODUCT_ELECTRICITY =  'Electricity';
    Public static final String ADMIN_FEE = 'Admin Fee';
    Public static final String DNE_ADMIN_FEE = 'DNE Admin Fee';
    Public static final String DISCOUNT = 'Discount';
    Public static final String PRODUCT_GAS =  'Gas';
    Public static final String SIZE_LARGE =  'Large';
    Public static final String SIZE_SMALL =  'Small';
    Public static final String PRICE_TYPE_CUSTOM ='Custom';
    Public static final String MARGIN_MAX = 'Margin Max';
    public static final string MARGIN_MIN = 'Margin Min';
    public static final string INVOICE_TYPE_UPFRONT = 'Upfront';
    public static final string INVOICE_TYPE_RESIDUAL = 'Residual';
    public static final string INVOICE_PAYMENT_RECEIVED = 'Payment Received';
    public static final string INVOICE_PAYMENT_LESS = 'Payment Less Than Exp. Amount Exceed Error Margin';
    public static final string INVOICE_PAYMENT_GREATER = 'Payment Greater Than Exp. Amount Exceed Error Margin';
    public static final string INVOICE_PAYMENT_LESS_ERROR_MARGIN = 'Payment Less Than Exp. Amount Within Error Margin';
    public static final string INVOICE_PAYMENT_GREATER_ERROR_MARGIN = 'Payment Greater Than Exp. Amount Within Error Margin';
   	Public static final String DISPUTE_STATUS_OK = 'Ok';
    Public static final String DISPUTE_STATUS_IN_DISPUTE = 'In Dispute';
    Public static final String DISPUTE_STATUS_DISPUTE_RESOLVED = 'Dispute Resolved';
    
    public static final string INVOICE_RECEIVED_PAYMENT = 'Payment Received';
    public static final string INVOICE_NOT_RECEIVED_PAYMENT = 'Payment Not Received';
    public static final string INVOICE_LESS_AMOUNT = 'Revenue is less than expected';
    public static final string INVOICE_GREATER_AMOUNT = 'Revenue is greater than expected';
    public static final string INVOICE_LESS_ADDER = 'Fee is less than expected';
    public static final string INVOICE_GREATER_ADDER = 'Fee is greater than expected';
    public static final string INVOICE_LESS_VOLUME = 'Volume less than expected';
   	Public static final String INVOICE_GREATER_VOLUME = 'Volume higher than expected';
    Public static final String INVOICE_CANCELLED = 'CANCELLED';
    Public static final String INVOICE_NOT_APPROVED = 'Site Drop not approved';
    public static final String CORRECT_CONTRACT_MISSING_SITE = 'Correct Contract & Missing Site';
    public static final String MISSING_CONTRACT_CORRECT_SITE = 'Missing Contract & Correct Site';
    public static final String MISSING_CONTRACT_MISSING_SITE = 'Missing Contract & Missing Site';
    
    
}